[build]
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "https://deploy-social-media-ap1.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
