[build]
  command = "npm run build"
  publish = "build"
  # Set the environment variables here if required
  environment = { 
    REACT_APP_API_URL = "https://deploy-social-media-ap1.onrender.com/api" 
  }

[[redirects]]
  from = "/api/*"
  to = "https://deploy-social-media-ap1.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
