export const Users = [
    {
      id: 1,
      profilePicture: `user/user1.jpg`,
      username: "Ayushi Singh",
    },
    {
      id: 2,
      profilePicture: `user/user2.jpg`,
      username: "Riya Singh",
    },
    {
      id: 3,
      profilePicture: `user/user3.jpg`,
      username: "Ankit Kumar",
    },
    {
      id: 4,
      profilePicture: `user/user4.jpg`,
      username: "Akansha",
    },
    {
      id: 5,
      profilePicture: `user/user5.jpg`,
      username: "Priya Rai",
    },
    {
      id: 6,
      profilePicture: `user/user6.jpg`,
      username: "Sachin Kumar",
    },
    {
      id: 7,
      profilePicture: `user/user7.jpg`,
      username: "Arjun Dev",
    },
    {
      id: 8,
      profilePicture: `user/user8.jpg`,
      username: "Om Prakash",
    },
    {
      id: 9,
      profilePicture: `user/user9.jpg`,
      username: "Saurabh Singh",
    },
    {
      id: 10,
      profilePicture: `user/user10.jpg`,
      username: "Arjun Chauhan",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/post1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/post2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/post3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/post5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/post11.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/post12.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/post13.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/post9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/post10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  